name: Setup Simply

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: Amorfx/simply-docker
          ref: main
          path: simply-docker
      - uses: actions/checkout@v4
        with:
          path: simply-docker/simply
      - name: Build and run
        run: docker compose up --build -d
        working-directory: simply-docker
      - name: Wait for install
        run: sleep 30
        working-directory: simply-docker
      - name: Verify install
        run: curl http://example.test
        working-directory: simply-docker
